var array = [1, 2, 3, 4, 5, 6];
var object = { one: 1, "two": "two", three: [3] };
var c;
var d = null;
var str = "HELLO I AM STRING";
console.log(array);
console.log(`The variable ${array} is of type ${typeof array}`);
console.log(object);
console.log(`The variable ${object} is of type ${typeof object}`);
console.log(c);
console.log(`The variable ${c} is of type ${typeof c}`);
console.log(d);
console.log(`The variable ${d} is of type ${typeof d}`);
console.log(object['one']);
console.log(`The variable ${object['one']} is of type ${typeof object['one']}`);
console.log(str);
console.log(`The variable ${str} is of type ${typeof str}`);